### ISSUE TITLE
Email notifications don't work

### ISSUE THREAD

**Issue by Fietspomp86** [OpenMediaVault-Plugin-Developers/openmediavault-anacron#1]
Hi,

I'm using the plugin on the latest OMV 5.0.
When setting up anacron jobs via the gui, the email function doesn't work.

Here's a line from the anacrontab file, after ticking the box emails:
`1    0    13    /usr/sbin/omv-backup | mail -E -s "Anacron - OMV Backup" -a "From: Anacron Daemon <root>" >/dev/null 2>&1`

While it should be:
`1    0    13    /usr/sbin/omv-backup | mail -E -s "Anacron - OMV Backup" -a "From: Anacron Daemon <root>" root >/dev/null 2>&1`

As you can see, the receipent is missing after the subject. Therefore the job will fail as it will not send an email.

Normal crontab looks like this when created from the gui:
`15 * * * * root /var/lib/openmediavault/cron.d/userdefined-252a483b-1dcf-4b05-aded-1715f1ddbcba | mail -E -s "Cron - Spotweb retrieve" -a "From: Cron Daemon <root>" root >/dev/null 2>&1`

When I add the `root` part the anacrobtab file manually, the emails work fine.

I've opened a PR #2 , I've edited the line on my system and it looks promising.

What I think is it's handled in this line
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-anacron/blob/ff10afa375c76b0680385c421399eda526c0e6de/srv/salt/omv/deploy/anacron/10omvanacron.sls#L8

And it should be changed into
`    - text: "{{ task.period }}\t{{ task.delay }}\t{{ task.identifier }}\t{{ task.command }} | mail -E -s \"Anacron - {{ task.comment | replace('\n', ' ') }}\" -a \"From: Anacron Daemon <{{ task.username }}>\" {{ task.username }} {{ end }}" `

**Comment by Fietspomp86** [comment]
Fixed with PR #2

**Comment by ryecoaaron** [comment]
5.0.2 in repo now.
