### ISSUE TITLE
Plugin not visible after installation

### ISSUE THREAD

**Issue by wiphi** [OpenMediaVault-Plugin-Developers/openmediavault-anacron#3]
I'm not shure, if its a bug at all, or a strange behavior on my system. But after the installtion of the anacron-plugin, it was not visible in the backend. Reinstallation or reboot doesn't help.

I had to run
`source /usr/share/openmediavault/scripts/helper-functions && omv_purge_internal_cache`
manually on the console, then the plugin was visible in the backend.

**Comment by ryecoaaron** [comment]
This was probably a browser cache issue on your side. The apt clean button in omv-extras will purge the internal cache without needing to use command line.
