### ISSUE TITLE
Email notifications don't work - when no comment is set

### ISSUE THREAD

**Issue by ludwigo82** [OpenMediaVault-Plugin-Developers/openmediavault-anacron#4]
Hi,

I was just wondering why most of my entries created with the web-GUI didn't trigger an email although configured to send email.

In the /etc/anacrontab problematic entries looked like this:
1       0       test_anacron_0  ls >/dev/null 2>&1

Non problematic entries looked like this:
1       0       test_anacron_0  ls | mail -E -s "test comment" -a "From: Anacron Daemon <root>" root>/dev/null 2>&1

After some testing I found out, that the mail-command was only attached, wenn a comment was set in the GUI.
If I removed the comment, the mail-command was also removed.

The comment-field is not mandatory when "send email" is activated, so I did not know I needed to fill it.

I assume this is a bug (or is it intended?).

Sorry if my english is not perfect.

Thank you so much for providing this plugin for free.

**Comment by ryecoaaron** [comment]
I have no idea why I wrote this line the way I did - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-anacron/blob/master/srv/salt/omv/deploy/anacron/10omvanacron.sls#L4  I will have to fix it.

**Comment by ryecoaaron** [comment]
5.0.3 is in the repo now.
